name: 'Add to changelog'
description: 'Prepends text to the changelog'
inputs:
  version:
    description: The version to add to the changelog
    required: true
  body:
    description: Content to be appended to the changelog
    required: true
  pr-url:
    description: The url to the pull request
    required: false
    default: ''
  changelog-path:
    description: The relative path to the changelog file
    required: false
    default: 'CHANGELOG.md'
  user-email:
    description: The email of the user that commits the CHANGELOG
    required: false
    default: github-actions[bot]@users.noreply.github.com
  user-name:
    description: The name of the user that commits the CHANGELOG
    required: false
    default: github-actions[bot]

runs:
  using: 'node16'
  main: 'release/index.js'
