name: Establish Context and Release

on:
  pull_request:
    types: [closed]

jobs:
  build:
    name: Establish Context and Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup node v16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: yarn
      name: Install dependencies
    - run: yarn build
      name: Build local action
    - name: Establish context
      id: context
      uses: woksin-org/establish-context-action@v4
    - name: Prepend to Changelog
      if: ${{ steps.context.outputs.should-publish == 'true' && steps.context.outputs.release-type != 'prerelease' }}
      uses: ./
      with:
        version: ${{ steps.context.outputs.new-version }}
        body: ${{ steps.context.outputs.pr-body }}
        pr-url: ${{ steps.context.outputs.pr-url }}
    - name: Create GitHub Release
      if: ${{ steps.context.outputs.should-publish == 'true' }}
      uses: woksin-org/github-release-action@v3
      with:
        version: ${{ steps.context.outputs.new-version }}
        body: ${{ steps.context.outputs.pr-body }}
        token: ${{ secrets.BUILD_PAT  }}
